# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
## a) Addition of 2 in all the element
## b) Multiply 3 with all the elements 
## c) Divide every element by 2

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)
# (a)
addition = arr + 10
print("After adding 10:", addition)
# (b)
multiplication = arr * 2
print("After multiplying by 2:", multiplication)
# (c)
division = arr / 10
print("After dividing by 10:", division)

Original Array: [10 20 30 40 50]
After adding 10: [20 30 40 50 60]
After multiplying by 2: [ 20  40  60  80 100]
After dividing by 10: [1. 2. 3. 4. 5.]


# Q.2 Questions on Basic NumPy Array:
## a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
## b) Find the most frequent value and their indice(s) in the following arrays:
### i. x = np.array([1,2,3,4,5,1,2,1,1,1])
### ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
# (a)
arr = np.array([1, 2, 3, 6, 4, 5])

reverse_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reverse_arr)

# (b)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(x == most_frequent)[0]

print("Array:", x)
print("Most frequent value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)

# (c)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(y == most_frequent)[0]

print("Array:", y)
print("Most frequent value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]
Array: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
## a) Access 1st row, 2nd column
## b) Access 3rd row, 1st column

In [6]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Array:")
print(arr)

print("1st row, 2nd column:", arr[0, 1])

print("3rd row, 1st column:", arr[2, 0])

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [11]:
MyArray = np.linspace(10, 100, 25)

print("Array:")
print(MyArray)

print("Dimensions:", MyArray.ndim)

print("Shape:", MyArray.shape)

print("Total elements:", MyArray.size)

print("Data type:", MyArray.dtype)

print("Total bytes:", MyArray.nbytes)

transpose_array = MyArray.reshape(25, 1)

print("Transpose using reshape():")
print(transpose_array)

transpose_T = MyArray.reshape(25, 1).T

print("Transpose using T attribute:")
print(transpose_T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


# Q5. Create a 2-D Array of three rows and four columns, named ucs420_your_name with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_your_name. Resize the array to two rows and three columns and name it as resized_ ucs420_your_name.

In [13]:
ucs420_Harshit_Goyal = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Harshit_Goyal)

print("Mean:", np.mean(ucs420_Harshit_Goyal))

print("Median:", np.median(ucs420_Harshit_Goyal))

print("Maximum:", np.max(ucs420_Harshit_Goyal))

print("Minimum:", np.min(ucs420_Harshit_Goyal))

print("Unique Elements:", np.unique(ucs420_Harshit_Goyal))

reshaped_ucs420_Harshit_Goyal = ucs420_Harshit_Goyal.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_Harshit_Goyal)

resized_ucs420_Harshit_Goyal = np.resize(ucs420_Harshit_Goyal, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_Harshit_Goyal)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
