# Q1. Consider the following sensor readings: temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
# A sensor has an average measurement error of +2°C. Perform the following without using a for loop:
## a. Add 2°C to every reading using vectorization.
## b. Convert all temperatures from Celsius to Fahrenheit using:
## F = 9/5 C + 32
## c. Identify all readings greater than 32°C using Boolean indexing.
## d. Count how many readings exceed 32°C.
## e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# (a)
corrected_temperature = temperature + 2

print("Original Temperature:", temperature)
print("Corrected Temperature:", corrected_temperature)

# (b)
fahrenheit = (9/5) * corrected_temperature + 32

print("Temperature in Fahrenheit:", fahrenheit)

# (c) 
readings_greater_32 = corrected_temperature[corrected_temperature > 32]

print("Readings greater than 32°C:", readings_greater_32)

# (d)
count = np.sum(corrected_temperature > 32)

print("Number of readings exceeding 32°C:", count)

Original Temperature: [25 28 31 35 38 27 33 40]
Corrected Temperature: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


# Q2. The following matrix represents the number of daily steps recorded by four users over three days:
#### steps = np.array([
#### [5000, 6200, 7100],
#### [8000, 7500, 9000],
#### [4500, 5100, 4800],
#### [9000, 8500, 9500]])

## Perform the following:
### a. Calculate the total steps recorded.
### b. Calculate the mean number of steps.
### c. Find the maximum and minimum values.
### d. Calculate the total steps for each day using axis=0.
### e. Calculate the total steps for each user using axis=1.
### f. Find the user/day position containing the maximum number of steps using argmax().

In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps Array:")
print(steps)

# (a) 
total_steps = np.sum(steps)
print("\na) Total steps:", total_steps)

# (b) 
mean_steps = np.mean(steps)
print("b) Mean steps:", mean_steps)

# (c) 
maximum = np.max(steps)
minimum = np.min(steps)

print("c) Maximum steps:", maximum)
print("   Minimum steps:", minimum)

# (d)
total_each_day = np.sum(steps, axis=0)
print("d) Total steps for each day:", total_each_day)

# (e) 
total_each_user = np.sum(steps, axis=1)
print("e) Total steps for each user:", total_each_user)


# (f)
max_position = np.argmax(steps)

print("f) Position of maximum value using argmax():", max_position)

row, column = np.unravel_index(np.argmax(steps), steps.shape)

print("   User number:", row + 1)
print("   Day number:", column + 1)

Steps Array:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]

a) Total steps: 84200
b) Mean steps: 7016.666666666667
c) Maximum steps: 9500
   Minimum steps: 4500
d) Total steps for each day: [26500 27300 30400]
e) Total steps for each user: [18300 24500 14400 27000]
f) Position of maximum value using argmax(): 11
   User number: 4
   Day number: 3


# Q3. Write a Python program using NumPy to perform the following operations:
## a. Create the following NumPy array: original = np.array([1, 2, 3, 4, 5, 6])
## b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.
## c. Modify the first element of subset to 999 and display both original and subset.
## d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array.
## e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.
## f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
#### • First row
#### • Last row
#### • Second column
#### • Elements from rows 1–2 and columns 2–3
## g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().
## h. Modify an element in the array returned by ravel() and observe whether the original array is affected.
## i. Modify an element in the array returned by flatten() and observe whether the original array is affected.
## j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [3]:
# (a)
original = np.array([1, 2, 3, 4, 5, 6])

print("a) Original array:")
print(original)

# (b)
subset = original[1:4]

print("\nb) Subset:")
print(subset)

# (c) 
subset[0] = 999

print("\nc) After modifying subset:")
print("Original:", original)
print("Subset:", subset)

# (d) 
copied_array = original[1:4].copy()

copied_array[0] = 500

print("\nd) After modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)

# (e) 
matrix = np.arange(1, 13).reshape(3, 4)

print("\ne) 3 x 4 Matrix:")
print(matrix)

# (f) 

first_row = matrix[0, :]
print("\nFirst row:")
print(first_row)

last_row = matrix[-1, :]
print("Last row:")
print(last_row)

second_column = matrix[:, 1]
print("Second column:")
print(second_column)

selected_elements = matrix[1:3, 2:4]

print("Elements from rows 1-2 and columns 2-3:")
print(selected_elements)

# (g)
flattened_array = matrix.flatten()
ravel_array = matrix.ravel()

print("\ng) Using flatten():")
print(flattened_array)

print("Using ravel():")
print(ravel_array)

# (h) 
ravel_array[0] = 1000

print("\nh) After modifying ravel array:")
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)

# (i) 
flattened_array[1] = 2000

print("\ni) After modifying flatten array:")
print("Flattened array:", flattened_array)
print("Original matrix:")
print(matrix)


# (j)
print("\nj) Properties of original 3 x 4 matrix:")
print("Shape:", matrix.shape)
print("Dimensions (ndim):", matrix.ndim)
print("Size:", matrix.size)
print("Data type (dtype):", matrix.dtype)

a) Original array:
[1 2 3 4 5 6]

b) Subset:
[2 3 4]

c) After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4]

d) After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4]

e) 3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]
Last row:
[ 9 10 11 12]
Second column:
[ 2  6 10]
Elements from rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

g) Using flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

h) After modifying ravel array:
Ravel array: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

i) After modifying flatten array:
Flattened array: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

j) Properties of original 3 x 4 matrix:
Shape: (3, 4)
Dimen

# Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors:
#### • Sleep hours
#### • Activity level
#### • Stress level
### Consider:
#### X = np.array([
#### [6, 70, 3],
#### [5, 50, 6],
#### [8, 80, 2],
#### [4, 30, 8]
#### ])
#### y = np.array([40, 65, 30, 85])
## Here, each row represents one user and each column represents a feature.
## Perform the following:
## a. Display the shape and dimensions of X.
## b. Calculate: X.T and explain what the transpose represents.
## c. Calculate the matrix product: X.T @ X
## d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.
## e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋!𝑋)"#𝑋!𝑦 using NumPy.
## f. Explain what the resulting coefficients represent in the context of the three user features.
## g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.

In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# (a)
print("a) Shape of X:", X.shape)
print("   Dimensions of X:", X.ndim)

# (b)
XT = X.T

print("\nb) Transpose of X:")
print(XT)

print("\nX represents:")
print("Rows = Users")
print("Columns = Features: Sleep Hours, Activity Level, Stress Level")

print("\nX.T represents:")
print("Rows = Features")
print("Columns = Users")

# (c)
XTX = X.T @ X

print("\nc) X.T @ X:")
print(XTX)

# (d) 
XTX_inv = np.linalg.inv(XTX)

print("\nd) Inverse of X.T @ X:")
print(XTX_inv)

# (e)
beta = XTX_inv @ X.T @ y

print("\ne) OLS Coefficients (Beta):")
print(beta)

# (f)
print("\nf) Coefficient interpretation:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

# (g)
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\ng) New User:", new_user)
print("Predicted Assistance Score:", predicted_score)

a) Shape of X: (4, 3)
   Dimensions of X: 2

b) Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X represents:
Rows = Users
Columns = Features: Sleep Hours, Activity Level, Stress Level

X.T represents:
Rows = Features
Columns = Users

c) X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d) Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e) OLS Coefficients (Beta):
[-0.15921454  0.14083853 10.06302242]

f) Coefficient interpretation:
Sleep coefficient: -0.15921454159528636
Activity coefficient: 0.14083852991907175
Stress coefficient: 10.063022422714596

g) New User: [ 5 40  7]
Predicted Assistance Score: 75.27862544778861
